title: zzz
frequency: 3
dirfilter:
- tmp
- .git
- public
- scripts
- vendor
- logs
- doc
- data
- custom
- conf
- assets
- .packager
- sh
ext:
- go
enablerun: true
action:
  before:
  - go generate internal/assets/conf/conf.go
  - go generate internal/assets/public/public.go
  - go generate internal/assets/templates/templates.go
  after:
  - ps -ef|grep 'gogs web'| grep -v grep | awk '{print $2}' | xargs kill -9  && ./gogs web &
link: https://github.com/midoks/zzz
